version: '3.3'
services:
  mydscan:
    build:
      context: .
      args:
        owner: root
    container_name: dscandb
    environment:
      MYSQL_DATABASE: 'ssldb'
      MYSQL_USER: 'fpuser'
      MYSQL_PASSWORD: 'xxxxx'
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - ./dscandb:/var/lib/mysql:rw
      - ./mysql-init-files:/docker-entrypoint-initdb.d
volumes:
  dscandb: {}
